name: Lulbaite
api-version: 1.19
description: LuaJ based scripting for Spigot and Paper
author: Xeno
website: https://github.com/xeno-fi/lulbaite/
softdepend: [XServerUtils, XSurvivalUtils, Amethyst, CoreProtect, WorldEdit, WorldGuard, FastAsyncWorldEdit, Vault, HolographicDisplays, ProtocolLib]
commands:
  xscript:
    description: Lulbaite administrative commands
    permission: xscript.admin
    aliases: [lulbaite, xs]
permissions: 
  xscript.admin:
    description: Permission to manage and use the plugin
version: 0.2.3
main: fi.lehtodigital.xeno.lulbaite.XenoScriptPlugin
